config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get '/signup' , to:'users#new'

  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy' 
  
  resources :users

  resources :entries #, only: [:create,:destroy]
  
  resources :users do
  	member do
  		get :following, :followers
  	end
  end

  resources :relationships,       only: [:create, :destroy]
  
  resources :comments
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  default_scope -> {order(created_at: :desc)}
  belongs_to :user
  belongs_to :entry
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
      @comment= current_user.comments.build(comment_params)
      if @comment.save
      	flash[:success] ="success commented"
      	redirect_to :back
      else
      	flash.now[:danger] = "error"
      end
  end

  private
  def comment_params
  	params.require(:comment).permit(:content, :entry_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
   <%= link_to gravatar_for(comment.user, size:50), comment.user %>
   <span class="user"><%= link_to comment.user.name, comment.user %></span>
   <span class="content"><%=comment.content %></span>
   <span class="timestamp">
   	Posted <%= time_ago_in_words(comment.created_at) %> ago.
   	<% if current_user?(comment.user) %>
   	<%= link_to "Edit", edit_comment_path(comment) %>
   	<%= link_to "delete", comment, method: :delete, data: { confirm: "Are you sure?"} %>
   	<% end %>
   </span>	
  