config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get '/signup' , to:'users#new'

  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy' 
  
  resources :users

  resources :entries #, only: [:create,:destroy]
  
  resources :users do
  	member do
  		get :following, :followers
  	end
  end

  resources :relationships,       only: [:create, :destroy]
  
  resources :comments
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  has_many :comments, :dependent => :destroy
  default_scope -> {order(created_at: :desc)}
  validates :content,presence: true, length:{maximum:140}
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	before_action :logged_in_user,only: [:create,:destroy]

	def create
		@entry=current_user.entries.build(entry_params)
		if @entry.save
			flash[:success]="Entry created"
			redirect_to root_url
		else
			@feed_items=[]
			render 'pages/home'
		end
	end
     
	def index
		@entries=Entry.paginate(page: params[:page])
	end
    
    def show
    	@entry=Entry.find(params[:id])
    	@comments=@entry.comments.paginate(page: params[:page])
    end

    private
    def entry_params
    	params.require(:entry).permit(:content,:title)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.erb
<li id="entries-<%=entry.id%>">
  <%= link_to gravatar_for(entry.user,size: 50),entry.user %>
 <!-- <span class="user"><%=link_to entry.user.name,entry.user %></span>-->
  <span class="title"><i><%= entry.title %></i></span>
  <span class="content"><%= link_to entry.content,entry_path(entry) %></span>
  <span class="timestamp">
  	Posted <%=time_ago_in_words(entry.created_at) %> ago
  </span>
  <%if logged_in? %>
     <% if current_user.following?(entry.user)||current_user==entry.user %>
       <%=link_to "Add a comment",entry_path(entry) %>
       <% end %>
  <% end %>
</li>

app/views/entries/index.html.erb
<% provide(:title,"All Entry") %>
<h1>All Entry</h1>

<%= will_paginate %>

<ul class="entries">
   <%= render @entries %>	
</ul>

<%= will_paginate %>

app/views/entries/show.html.erb
<div class="row">
   <aside class="col-md-4">
     <section>
        <%= link_to gravatar_for(@entry.user,size: 50),@entry.user %>
        <span class="title"><i><%= @entry.title %></i></span>
        <span class="content"><%= @entry.content %></span>
        <span class="timestamp">
          Posted <%=time_ago_in_words(@entry.created_at) %> ago
        </span>
     </section>
     <section>
        <% if logged_in? %>
        <%= form_for(comment ||= current_user.comments.build) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="field">
          <%= f.text_area :content, placeholder: "Compose a comment..." %>
          <%= f.hidden_field :entry_id, value: @entry.id %>
        </div>
        <%= f.submit "Comment", class: "btn btn-primary" %>
        <% end %>
        <%end %>
     </section>
   </aside>
   <div class="col-md-8">
       <h3>Comments(<%=@entry.comments.count %>)</h3>
       <div>
         <% if @entry.comments.any? %>
         <ol class="entries">
           <%= render @comments %>
         </ol>
         <% will_paginate @comments %>
         <%end %>
       </div>
  </div>
</div>