config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get '/signup' , to:'users#new'

  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy' 
  
  resources :users

  resources :entries #, only: [:create,:destroy]
  
  resources :users do
  	member do
  		get :following, :followers
  	end
  end

  resources :relationships,       only: [:create, :destroy]
  
  resources :comments
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Copyright &copy; <a href="#">The complete Ruby on rails Developer</a> by Lin Nguyen
		</small>
		<nav>
			<ul>
				<li><%= link_to "About",'#' %></li>
			</ul>
		</nav>
	</footer>
</div>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to "My blog",root_path ,class:"navbar-brand"%>
      <%= link_to "Entry",entries_path,class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
       <ul class="nav navbar-nav navbar-right">
        <li><%=link_to "Home",root_path %></li>
        <% if logged_in? %>
         <li><%=link_to "Users",users_path%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Setting',edit_user_path(current_user) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Log out',logout_path, method: 'delete' %></li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to 'Login',login_path %></li>
           <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demoapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  

  <body>
    <%= render '/layouts/nav_bar' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

    	<%= yield %>
    	<%=  render '/layouts/footer' %>
    </div>
  </body>
</html>